# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'EduSearch' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Database'


  target 'EduSearchTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'EduSearch-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EduSearch-tvOS

  target 'EduSearch-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
